basePath: /
consumes:
    - application/json
definitions:
    Product:
        x-go-package: github.com/mohammad-quanit/Go-Microservices-App/data
info:
    description: '# Documentation for Product API'
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            description: Return a list of products from the database
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            tags:
                - products
produces:
    - application/json
responses:
    productsResponse:
        description: ProductsResponseWrapper represents the response wrapper for products.
        schema:
            items: {}
            type: array
schemes:
    - http
swagger: "2.0"
